// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMoJgOGHQwbIplcwkRoovKDXpB2WgysQ',
    appId: '1:517434290085:web:631e2b47f182309caa824c',
    messagingSenderId: '517434290085',
    projectId: 'flutterfire-ui-codelab-af6e2',
    authDomain: 'flutterfire-ui-codelab-af6e2.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-af6e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2nU6Opmu7UA9G6LpTbm8YHjmSnSb1SU',
    appId: '1:517434290085:android:dcba194f32d3fa3daa824c',
    messagingSenderId: '517434290085',
    projectId: 'flutterfire-ui-codelab-af6e2',
    storageBucket: 'flutterfire-ui-codelab-af6e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBvxo_xFNY7CoURO-YLQiyVvkHzOOEwQ',
    appId: '1:517434290085:ios:baf2f58007a3db2aaa824c',
    messagingSenderId: '517434290085',
    projectId: 'flutterfire-ui-codelab-af6e2',
    storageBucket: 'flutterfire-ui-codelab-af6e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsBvxo_xFNY7CoURO-YLQiyVvkHzOOEwQ',
    appId: '1:517434290085:ios:baf2f58007a3db2aaa824c',
    messagingSenderId: '517434290085',
    projectId: 'flutterfire-ui-codelab-af6e2',
    storageBucket: 'flutterfire-ui-codelab-af6e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoMoJgOGHQwbIplcwkRoovKDXpB2WgysQ',
    appId: '1:517434290085:web:1ff8523ec239f4bcaa824c',
    messagingSenderId: '517434290085',
    projectId: 'flutterfire-ui-codelab-af6e2',
    authDomain: 'flutterfire-ui-codelab-af6e2.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-af6e2.firebasestorage.app',
  );
}
